[workspace]

members = [
    "demo-clickgrid",
    "linux-wm",
    "test-wm",
    "demo-moveplayer",
    "central",
    "graphics_tests",
    "tools-input",
    "common",
    "plat",
    "devtools"
]
