[workspace]

members = [
    "digital-clock",
    "linux-wm",
    "test-wm",
    "echo-app",
    "central",
    "graphics_tests",
    "tools-input",
    "common",
    "plat",
    "devtools/mainmain",
    "devtools/runner",
    "test-log",
]
