[workspace]

members = [
    "central",
    "common",
    "db",
    "gfx",
    "minibuf",
    "plat",
    "tools/runner",
]

default-members = [
    "central",
    "common",
    "db",
    "gfx",
    "minibuf",
    "plat",
    "tools/runner",
]
