[workspace]

members = [
    "digital-clock",
    "echo-app",
    "central",
    "tools-input",
    "common",
    "plat",
    "devtools/runner",
    "test-log",
    "uitoolkit",
    "uitoolkit/toolbar-mock"
]
