[package]
name = "graphics_tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path="../common"}
log4rs = "1.0.0"
libc = "0.2"
framebuffer = "0.3.1"
